### ISSUE TITLE
flutter vimeo player issue

### ISSUE THREAD

**Issue by susil07** [Mindinventory/vimeo_video_player#23] opened 2023-04-26 10:40 UTC
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
video link-https://vimeo.com/818639646
@pratikmi @akashmi @piotrszych @mehulrajput

**Comment by mohit-chauhan-mi** [comment] 2023-04-26 12:41
@susil07
The issue is with the Vimeo Public API itself. we're using this value to load the video inside the player but for this, we're getting an empty list. That's why you are getting an exception. Kindly try using other videos.

Closing this for now, will inform you if we get any update from Vimeo Public API.

![Screenshot 2023-04-26 at 5 29 28 PM](https://user-images.githubusercontent.com/71555515/234576579-9b8c1efb-d6da-4079-b1f7-ee71c3e3a0cc.png)

**Closed by mohit-chauhan-mi** 2023-04-26 12:41 UTC

**Comment by susil07** [comment] 2023-04-27 04:36
Is there any other way to play this video or I need to pass any different
requirements.
  Please let me know, it will greatly help me.

Thank you.

**Comment by mohit-chauhan-mi** [comment] 2023-04-28 05:19
@susil07 
Right now there is no other way to do this, if we find anything then will update you. Thanks.
