### ISSUE TITLE
error flull screen ios 

### ISSUE THREAD

**Issue by fredy2010111** [Mindinventory/vimeo_video_player#33] opened 2023-08-16 22:56 UTC
in ios no rotate video when is full screen

**Comment by mohit-chauhan-mi** [comment] 2024-02-14 09:46
We're not able to reproduce this issue, closing this for now feel free to re-open it if it's still exists. 
Please check it with the [latest version](https://pub.dev/packages/vimeo_video_player). Thanks.

**Closed by mohit-chauhan-mi** 2024-02-14 09:46 UTC
